citycouncil/settings.py, citycouncil/urls.py, comparison/admin.py, comparison/apps.py, comparison/models.py, comparison/templates/comparison/compare.html, comparison/tests.py, comparison/urls.py, comparison/views.py, overview/models.py, overview/templates/overview/candidate_card.html, overview/templates/overview/candidate_list.html, overview/utils.py, overview/views.py, templates/base.html
Right now, this is keyed liked `/compare/?cand=alexriina&cand=jim` but we can change that to be whatever you like
=> Comparison page

overview/admin.py
and rendering the found image in the detail page
=> spruce up the candidate admin a bit

templates/base.html
=> add twitter button to footer

citycouncil/settings.py, overview/templates/overview/candidate_detail.html
=> add commas to money numbers

overview/templates/overview/candidate_detail.html, overview/templates/overview/candidate_list.html, overview/templatetags/overview.py
=> on hover show "view their answers"

.gitignore, Procfile, citycouncil/settings.py, package.json, static/base.css, static_src/candidate_sidebar.js, static_src/index.js, static_src/jquery.ui.touch-punch.min.js, templates/base.html, webpack.config.js
- `web:` gets run on each webserver and the webservers serve their own
static files instead of pushing them to a cdn so we much run that on
each web instead of on release which runs on its own dyno
=> webpackify for heroku

static_src/candidate_sidebar.js, templates/base.html
=> remove blue bar by setting sidebar visible only on show

templates/registration/password_reset_email.html
=> fix django path to password reset

campaign_finance/models.py, campaign_finance/templatetags/finance_extras.py, overview/templates/overview/candidate_detail.html, overview/templates/overview/index.html, overview/views.py
we don't have 2019 data from ocpf.us yet, but these labels and functions all need to be updated for new data to be useful anyway
bopped around the site, confirmed nothing (new) broke
=> update the years in the finance stuff to be 2019

overview/admin.py
=> add cpf id to the admin site

ranking/templates/ranking/detail.html
=> add help for empty slate

ranking/templates/ranking/detail.html
Move help text outside of #ranked_list
=> Maybe make help text not sortable

overview/templates/overview/candidate_detail.html
hmmm not sure I like my tweaks either 🤔
=> tweak the overview header change I just did because it looks silly

citycouncil/urls.py, templates/404.html
=> improve the look of the 404 page

ranking/templates/ranking/detail.html
=> improve the look of the ballot display, especially for longer names

templates/about_us.html, templates/registration/password_reset_complete.html, templates/registration/password_reset_done.html, templates/registration/password_reset_form.html
=> Password reset

.slugignore
Convince heroku that it doesn't need to generate static files for Kelsey
=> convince heroku to this is not node

overview/context_processors.py, overview/templates/overview/candidates_housing.html, overview/views.py, templates/base.html
Logout has to be a form in django registration. I think because we hadn't been pinning the version, we ended up upgrading when we started up the system again.
Also fixing one list indexing by candidate and one indexing by candidate election.
=> Fix mismatched indexing and make logout a form

overview/templates/overview/candidateelection_detail.html, ranking/templates/ranking/detail.html, templates/base.html
- fix quote display
- re add the append to ballot button (not working perfectly, but not horrible)
- re add notes form
- fix hamburger appearance
=> html fixes

django_app/current_elections.yaml, django_app/overview/factories.py, django_app/overview/tests.py, django_app/ranking/factories.py, django_app/ranking/models.py, django_app/ranking/signals.py, django_app/ranking/tests.py, django_app/ranking/views.py
Fix all of our tests or mark as expected failures for the things that I'll actually have to dig into.
=> fix overview and ranking tests
